import {
  WorkflowEntrypoint,
  WorkflowStep,
  WorkflowEvent,
} from "cloudflare:workers";

interface Env {
  AI: Ai;
}

interface PostmortemParams {
  state: {
    title: string;
    severity: string;
    hypothesis: string;
    actions: { text: string; done: boolean }[];
    findings: string[];
    messages: { role: string; content: string; timestamp: number }[];
    createdAt: number;
    updatedAt: number;
  };
}

export class PostmortemWorkflow extends WorkflowEntrypoint<Env, PostmortemParams> {
  async run(event: WorkflowEvent<PostmortemParams>, step: WorkflowStep) {
    const { state } = event.payload;

    // Step 1: Generate timeline from conversation
    const timeline = await step.do("generate-timeline", async () => {
      const conversationText = state.messages
        .map(
          (m) =>
            `[${new Date(m.timestamp).toISOString()}] ${m.role}: ${m.content}`
        )
        .join("\n");

      const res = await this.env.AI.run(
        "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        {
          messages: [
            {
              role: "system",
              content:
                "You are a postmortem writer. Given an incident conversation, produce a concise timeline of events as a markdown list. Each entry should have a timestamp and a one-sentence description of what happened or was discovered.",
            },
            { role: "user", content: conversationText },
          ],
        }
      );
      return typeof res === "string" ? res : (res as any).response ?? "";
    });

    // Step 2: Generate root cause analysis
    const rootCause = await step.do("root-cause-analysis", async () => {
      const context = `
Title: ${state.title}
Severity: ${state.severity}
Hypothesis: ${state.hypothesis}
Findings: ${state.findings.join("; ")}
Actions taken: ${state.actions.map((a) => `${a.text} (${a.done ? "done" : "pending"})`).join("; ")}
      `;

      const res = await this.env.AI.run(
        "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        {
          messages: [
            {
              role: "system",
              content:
                "You are a postmortem writer. Given incident context, write a clear root cause analysis in 2-3 paragraphs. Be specific and technical.",
            },
            { role: "user", content: context },
          ],
        }
      );
      return typeof res === "string" ? res : (res as any).response ?? "";
    });

    // Step 3: Generate "what went well / what to improve"
    const retrospective = await step.do("retrospective", async () => {
      const context = `
Title: ${state.title}
Findings: ${state.findings.join("; ")}
Actions: ${state.actions.map((a) => `${a.text} (${a.done ? "done" : "pending"})`).join("; ")}
Conversation length: ${state.messages.length} messages
Time from start to now: ${Math.round((state.updatedAt - state.createdAt) / 60000)} minutes
      `;

      const res = await this.env.AI.run(
        "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        {
          messages: [
            {
              role: "system",
              content:
                'Write a brief retrospective with two sections: "What went well" and "What to improve". Use bullet points. Be constructive and specific.',
            },
            { role: "user", content: context },
          ],
        }
      );
      return typeof res === "string" ? res : (res as any).response ?? "";
    });

    // Step 4: Assemble the final postmortem document
    const postmortem = await step.do("assemble-postmortem", async () => {
      return `# Postmortem: ${state.title}

**Severity:** ${state.severity}
**Status:** Resolved
**Duration:** ${Math.round((state.updatedAt - state.createdAt) / 60000)} minutes
**Generated:** ${new Date().toISOString()}

---

## Timeline

${timeline}

---

## Root Cause Analysis

${rootCause}

---

## Actions Taken

${state.actions.map((a) => `- [${a.done ? "x" : " "}] ${a.text}`).join("\n")}

---

## Retrospective

${retrospective}

---

*Auto-generated by Incident Response Copilot*
`;
    });

    return postmortem;
  }
}

// The worker needs a default export even though it mainly serves the workflow
export default {
  async fetch() {
    return new Response("Postmortem workflow worker. Triggered via API.");
  },
};